#!/usr/bin/env python
# tp.py

from __future__ import print_function

from optparse import OptionParser

import os
import re
import sys
import textwrap



class Word (object):

    """A word from the Toki Pona dictionary."""

    def __repr__ (self):
        return '{0}({1})'.format (self.__class__.__name__, self.word)

    def __init__ (self, word):
        self._word = word
        self._meanings = {}

    @property
    def meanings (self):
        """A dict of meanings."""
        return self._meanings

    @property
    def word (self):
        """The text of the word."""
        return self._word

    def add_meaning (self, part_of_speech, meaning):
        self.meanings[part_of_speech] = meaning

    def get_str (self, indices=[]):
        """Get a string for the word, optionally specifying certain meanings."""
        out = []
        out.append ('{0}\n{1}'.format (self.word, len (self.word) * '-'))
        if not indices:
            indices = range (len (self.meanings))
            meanings = sorted (self.meanings.iteritems ())
            for pos, meaning in meanings:
                meaning_indent = 4 + len (pos) + 2
                pos_str = '    {0}: '.format (pos)
                
                meaning_str = ('\n' + meaning_indent * ' ').join (
                        textwrap.wrap (meaning, 79 - meaning_indent))
                out.append (pos_str + meaning_str)
        return '\n'.join (out)


class WordList (object):

    """Provide a searchable Toki Pona dictionary."""

    _wordlist_str = \
        """
        ;a : ''interj'' ah, ha, uh, oh, ooh, aw, well (emotion word)
        ;akesi : ''n'' non-cute animal, reptile, amphibian
        ;ala : ''mod'' no, not, none, un-
        :''n'' nothing, negation, zero
        :''interj'' no!
        ;alasa : ''vt'' gather, hunt
        ;ale : ''n'' everything, anything, life, the universe
        :''mod'' all, every, complete, whole
        :''note'' formerly "ali"
        ;ali : ''n'' everything, anything, life, the universe
        :''mod'' all, every, complete, whole
        :''note'' now "ale"
        ;anpa : ''n'' bottom, lower part, under, below, floor, beneath
        :''mod'' low, lower, bottom, down
        ;ante : ''n'' difference
        :''mod'' different
        :''conj'' otherwise, or else
        :''vt'' change, alter, modify
        ;anu : ''conj'' or
        ;awen : ''vi'' stay, wait, remain
        :''vt'' keep
        :''mod'' remaining, stationary, permanent, sedentary
        ;e : ''sep'' (introduces a direct object)
        ;en : ''conj'' and (used to coordinate head nouns)
        ;esun : ''n'' market, shop
        ;ijo : ''n'' thing, something, stuff, anything, object
        :''mod'' of something
        :''vt'' objectify
        ;ike : ''mod'' bad, negative, wrong, evil, overly complex, (figuratively) unhealthy
        :''interj'' oh dear! woe! alas!
        :''n'' negativity, badness, evil
        :''vt'' to make bad, to worsen, to have a negative effect upon
        :''vi'' to be bad, to suck
        :[sounds like icky] 
        ;ilo : ''n'' tool, device, machine, thing used for a specific purpose
        ;insa : ''n'' inside, inner world, centre, stomach
        :''mod'' inner, internal
        :[inside] 
        ;jaki : ''mod'' dirty, gross, filthy
        :''n'' dirt, pollution, garbage, filth
        :''vt'' pollute, dirty
        :''interj'' ew! yuck!
        :[yucky] 
        ;jan : ''n'' person, people, human, being, somebody, anybody
        :''mod'' human, somebody's, personal, of people
        :''vt'' personify, humanize, personalize
        ;jelo : ''mod'' yellow, light green
        :[yellow] 
        ;jo : ''vt'' have, contain
        :''n'' having
        :''kama'' receive, get, take, obtain
        ;kala : ''n'' fish, sea creature
        ;kalama : ''n'' sound, noise, voice
        :''vi'' make noise
        :''vt'' sound, ring, play (an instrument)
        ;kama : ''vi'' come, become, arrive, happen, pursue actions to arrive to (a certain state), manage to, start to
        :''n'' event, happening, chance, arrival, beginning
        :''mod'' coming, future
        :''vt'' bring about, summon
        :[come up] 
        ;kasi : ''n'' plant, leaf, herb, tree, wood
        ;ken : ''vi'' can, is able to, is allowed to, may, is possible
        :''n'' possibility, ability, power to do things, permission
        :''vt'' make possible, enable, allow, permit
        :''cont'' it is possible that
        ;kepeken : ''vt'' use
        :''prep'' with
        ;kili : ''n'' fruit, pulpy vegetable, mushroom
        ;kin : ''mod'' also, too, even, indeed (emphasizes the word(s) before it)
        ;kipisi : ''(yet undefined entry in the official word list)''
        ;kiwen : ''mod'' hard, solid, stone-like, made of stone or metal
        :''n'' hard thing, rock, stone, metal, mineral, clay
        ;ko : ''n'' semi-solid or squishy substance, e.g. paste, powder, gum
        ;kon : ''n'' air, wind, smell, soul
        :''mod'' air-like, ethereal, gaseous
        ;kule : ''n'' colour, paint
        :''mod'' colourful
        :''vt'' colour, paint
        ;kulupu : ''n'' group, community, society, company, people
        :''mod'' communal, shared, public, of the society
        ;kute : ''vt'' listen, hear
        :''mod'' auditory, hearing
        ;la : ''sep'' (between adverb or phrase of context and sentence)
        ;lape : ''n, vi'' sleep, rest
        :''mod'' sleeping, of sleep
        ;laso : ''mod'' blue, blue-green
        ;lawa : ''n'' head, mind
        :''mod'' main, leading, in charge
        :''vt'' lead, control, rule, steer
        ;len : ''n'' clothing, cloth, fabric
        ;lete : ''n'' cold
        :''mod'' cold, uncooked
        :''vt'' cool down, chill
        ;li : ''sep'' "(between any subject except mi and sina and its verb; also used to introduce a new verb for the same subject)"
        ;lili : ''mod'' small, little, young, a bit, short, few, less
        :''vt'' reduce, shorten, shrink, lessen
        ;linja : ''n'' long, very thin, floppy thing, e.g. string, rope, hair, thread, cord, chain
        ;lipu : ''n'' flat and bendable thing, e.g. paper, card, ticket
        ;loje : ''mod'' red
        ;lon : ''prep'' be (located) in/at/on
        :''vi'' be there, be present, be real/true, exist, be awake
        ;luka : ''n'' hand, arm
        ;lukin : ''vt'' see, look at, watch, read
        :''vi'' look, watch out, pay attention
        :''mod'' visual(ly)
        :[looking] 
        ;lupa : ''n'' hole, orifice, window, door
        :[sounds like loop] 
        ;ma : ''n'' land, earth, country, (outdoor) area
        ;mama : ''n'' parent, mother, father
        :''mod'' of the parent, parental, maternal, fatherly
        :[sounds like momma] 
        ;mani : ''n'' money, material wealth, currency, dollar, capital
        :[money] 
        ;meli : ''n'' woman, female, girl, wife, girlfriend
        :''mod'' female, feminine, womanly
        :[Mary] 
        ;mi : ''n'' I, we
        :''mod'' my, our
        :[me] 
        ;mije : ''n'' man, male, boy, husband, boyfriend
        :''mod'' male, masculine, manly
        ;moku : ''n'' food, meal
        :''vt'' eat, drink, swallow, ingest, consume
        ;moli : ''n'' death
        :''vi'' die, be dead
        :''vt'' kill
        :''mod'' dead, deadly, fatal
        ;monsi : ''n'' back, rear end, butt, behind
        :''mod'' back, rear
        ;mu : ''interj'' woof! meow! moo! etc. (cute animal noise)
        :[moo] 
        ;mun : ''n'' moon
        :''mod'' lunar
        :[moon] 
        ;musi : ''n'' fun, playing, game, recreation, art, entertainment
        :''mod'' artful, fun, recreational
        :''vi'' play, have fun
        :''vt'' amuse, entertain
        ;mute : ''mod'' many, very, much, several, a lot, abundant, numerous, more
        :''n'' amount, quantity
        :''vt'' make many or much
        :[multi] 
        ;namako : ''n'' food additive, accessory, something extra
        :''vt'' season, embellish, stimulate
        ;nanpa : ''n'' number
        :''oth'' -th (ordinal numbers)
        :[number] 
        ;nasa : ''mod'' silly, crazy, foolish, drunk, strange, stupid, weird
        :''vt'' drive crazy, make weird
        ;nasin : ''n'' way, manner, custom, road, path, doctrine, system, method
        ;nena : ''n'' bump, nose, hill, mountain, button
        ;ni : ''mod'' this, that
        ;nimi : ''n'' word, name
        ;noka : ''n'' leg, foot
        ;o : ''sep'' O (vocative or imperative)
        :''interj'' hey! (calling somebody's attention)
        ;oko : ''n'' eye
        :[similar to oculist] 
        ;olin : ''n'' love
        :''mod'' love
        :''vt'' to love (a person)
        ;ona : ''n'' she, he, it, they
        :''mod'' her, his, its, their
        ;open : ''vt'' open, turn on
        ;pakala : ''n'' blunder, accident, mistake, destruction, damage, breaking
        :''vt'' screw up, fuck up, botch, ruin, break, hurt, injure, damage, spoil, ruin
        :''vi'' screw up, fall apart, break
        :''interj'' damn! fuck!
        ;pali : ''n'' activity, work, deed, project
        :''mod'' active, work-related, operating, working
        :''vt'' do, make, build, create
        :''vi'' act, work, function
        ;palisa : ''n'' long, mostly hard object, e.g. rod, stick, branch
        ;pan : ''n'' grain, cereal
        ;pana : ''vt'' give, put, send, place, release, emit, cause
        :''n'' giving, transfer, exchange
        ;pi : ''sep'' of, belonging to
        ;pilin : ''n'' feelings, emotion, heart
        :''vi'' feel
        :''vt'' feel, think, sense, touch
        :[feeling] 
        ;pimeja : ''mod'' black, dark
        :''n'' darkness, shadows
        :''vt'' darken
        ;pini : ''n'' end, tip
        :''mod'' completed, finished, past, done, ago
        :''vt'' finish, close, end, turn off
        ;pipi : ''n'' bug, insect, spider
        ;poka : ''n'' side, hip, next to
        :''prep'' in the accompaniment of, with
        :''mod'' neighbouring
        ;poki : ''n'' container, box, bowl, cup, glass
        :[box] 
        ;pona : ''n'' good, simplicity, positivity
        :''mod'' good, simple, positive, nice, correct, right
        :''interj'' great! good! thanks! OK! cool! yay!
        :''vt'' improve, fix, repair, make good
        :[bonam] 
        ;pu : ''(yet undefined entry in the official word list)''
        ;sama : ''mod'' same, similar, equal, of equal status or position
        :''prep'' like, as, seem
        ;seli : ''n'' fire, warmth, heat
        :''mod'' hot, warm, cooked
        :''vt'' heat, warm up, cook
        ;selo : ''n'' outside, surface, skin, shell, bark, shape, peel
        ;seme : ''oth'' what, which, wh- (question word)
        ;sewi : ''n'' high, up, above, top, over, on
        :''mod'' superior, elevated, religious, formal
        ;sijelo : ''n'' body, physical state
        ;sike : ''n'' circle, wheel, sphere, ball, cycle
        :''mod'' round, cyclical
        ;sin : ''mod'' new, fresh, another, more
        :''vt'' renew, renovate, freshen
        ;sina : ''n'' you
        :''mod'' your
        ;sinpin : ''n'' front, chest, torso, face, wall
        ;sitelen : ''n'' picture, image
        :''vt'' draw, write
        ;sona : ''n'' knowledge, wisdom, intelligence, understanding
        :''vt'' know, understand, know how to
        :''vi'' know, understand
        :''kama'' learn, study
        ;soweli : ''n'' animal, especially land mammal, lovable animal
        ;suli : ''mod'' big, tall, long, adult, important
        :''vt'' enlarge, lengthen
        :''n'' size
        ;suno : ''n'' sun, light
        ;supa : ''n'' horizontal surface, e.g furniture, table, chair, pillow, floor
        ;suwi : ''n'' candy, sweet food
        :''mod'' sweet, cute
        :''vt'' sweeten
        :[sweet] 
        ;tan : ''prep'' from, by, because of, since
        :''n'' origin, cause
        ;taso : ''mod'' only, sole
        :''conj'' but
        :[that's all] 
        ;tawa : ''prep'' to, in order to, towards, for, until
        :''vi'' go to, walk, travel, move, leave
        :''n'' movement, transportation
        :''mod'' moving, mobile
        :''vt'' move, displace
        :[towards] 
        ;telo : ''n'' water, liquid, juice, sauce
        :''vt'' water, wash with water
        ;tenpo : ''n'' time, period of time, moment, duration, situation
        ;toki : ''n'' language, talking, speech, communication
        :''mod'' talking, verbal
        :''vt'' say
        :''vi'' talk, chat, communicate
        :''interj'' hello! hi!
        ;tomo : ''n'' indoor constructed space, e.g. house, home, room, building
        :''mod'' urban, domestic, household
        ;tu : ''mod'' two
        :''n'' duo, pair
        :''vt'' double, separate/cut/divide in two
        :[two] 
        ;unpa : ''n'' sex, sexuality
        :''mod'' erotic, sexual
        :''vt'' have sex with, sleep with, fuck
        :''vi'' have sex
        ;uta : ''n'' mouth
        :''mod'' oral
        ;utala : ''n'' conflict, disharmony, competition, fight, war, battle, attack, blow, argument, physical or verbal violence
        :''vt'' hit, strike, attack, compete against
        ;walo : ''mod'' white, light (colour)
        :''n'' white thing or part, whiteness, lightness
        :[sounds like wall, which is often white] 
        ;wan : ''mod'' one, a
        :''n'' unit, element, particle, part, piece
        :''vt'' unite, make one
        :[one] 
        ;waso : ''n'' bird, winged animal
        ;wawa : ''n'' energy, strength, power
        :''mod'' energetic, strong, fierce, intense, sure, confident
        :''vt'' strengthen, energize, empower
        ;weka : ''mod'' away, absent, missing
        :''n'' absence
        :''vt'' throw away, remove, get rid of
        ;wile : ''vt'' to want, need, wish, have to, must, will, should
        :''n'' desire, need, will
        :''mod'' necessary"""

    def __init__ (self):
        words = self.words = []
        lines = map (str.strip, self._wordlist_str.split ('\n'))
        def handle_meaning (word, line):
            match = re.match (r".*: ?''(\w+)'' (.*)$", line)
            if match:
                word.add_meaning (*match.groups ())


        for line in lines:
            if not line:
                continue
            match = re.match (r'^;(\w+) :', line)
            if match:
                word = Word (match.group (1))
                words.append (word)
            handle_meaning (word, line)

    def get_word (self, word):
        """Get a Word for ``word``."""
        for w in self.words:
            if w.word == word:
                return w
        return None

    def get_words (self, search, pos=''):
        """Get Words for given regex match on meanings."""
        out = []
        for w in self.words:
            for p, m in w.meanings.iteritems ():
                match = re.search (search, m)
                if match and pos in (p, ''):
                    out.append (w)
                    break
        return out


class App (object):

    def run (self):
        usage = """%prog {[options]} [search]"""
        parser = OptionParser (usage=usage)
        parser.add_option ('-t', '--tokipona',
                action='store_const', const='tokipona', dest='domain',
                default='tokipona',
                help='search toki pona word list')
        parser.add_option ('-e', '--english',
                action='store_const', const='english', dest='domain',
                help='search english meanings')
        parser.add_option ('-p', '--partofspeech', dest='partofspeech',
                default='', metavar='PARTOFSPEECH',
                help='limit search to PARTOFSPEECH')
        opts, args = parser.parse_args ()

        search = args[0]

        wl = WordList ()

        if opts.domain == 'tokipona':
            word = wl.get_word (search)
            if word:
                print (word.get_str())
                return
            else:
                print ('no matching toki pona word found; '
                        'searching meanings...\n')
        words = wl.get_words (search, opts.partofspeech)
        for word in words:
            print (word.get_str ())
            print ()


if __name__ == '__main__':
    a = App ()
    a.run ()
